## It will create a container from centos:latest image unless set here, and will execute following stages inside.
## centos:latest is defined by default in config.toml file.
## runner is the "aws jenkins"

variables:
  goimage: "golang:1.12.1"

## spin-up a container from this image for all tasks.
image: $goimage

## stages for ci/cd
stages:
  - lint
  - build
  - test

## Lint stage
linter:
  stage: lint
  before_script:
    - go get -u golang.org/x/lint/golint
  script:
    - "echo '############ Starting Lint ###########'"
    - golint -set_exit_status
  tags:
    - awsrunner

## Build Stage
builder:
  stage: build
  before_script:
    - export GO111MODULE=on
  script:
    - "echo '############ Starting Build ###########'"
    - go mod tidy
    - go build *.go
  tags:
    - awsrunner

## Test Stage
tester:
  stage: test
  before_script:
    - export GO111MODULE=on
  script:
    - "echo '############ Starting Unit Tests ###########'"
    - go test *.go
  tags:
    - awsrunner
