## It will create a container from centos:latest image unless set here, and will execute following stages inside.
## centos:latest is defined by default in config.toml file.
## runner is the "aws jenkins"

variables:
  goimage: "golang:1.12.1"

## spin-up a container from this image for all tasks.
image: $goimage

## stages for ci/cd
stages:
  - build
  - test

## Build Stage
## Compile
compile:
  stage: build
  before_script:
    - mkdir ~/tmp
    - mkdir ~/tmp/$CI_PROJECT_NAME
    - cp -r . ~/tmp/$CI_PROJECT_NAME
    - cd ~/tmp/$CI_PROJECT_NAME
    - export GO111MODULE=on
    - git config --global url."https://".insteadOf git://
  script:
    - "echo '############ Starting Compile ###########'"
    - go mod tidy
    - go build *.go
    - "echo '############ Starting Unit Tests ###########'"
    - go test *.go
  tags:
    - awsrunner

## Test Stage
## Lint
lint test:
  stage: test
  before_script:
    - go get -u golang.org/x/lint/golint
  script:
    - golint -set_exit_status
  tags:
    - awsrunner
