app_port = 8080
# test_value = "testing"

[migrations]
dbdatasource = "postgres://secret@postgres:5432/db"

[keycloack]
ssobaseurl = "http://keycloak.test.com/"
ssopubkeyid = "keyid1234"
ssorealm = "finops"

[super_secret]
topsecret = "qwerty1234"
